### ISSUE TITLE
Look into building native executables

### ISSUE THREAD

**Issue by nscuro** [mehab/DTKafkaPOC#141]
Considering the containers are quite heavyweight right now (~500mb each), compiling for native may be a good way to reduce the final size of our images.

This will be a larger task, and may require significant amounts of refactoring, especially regarding code we ported over from the OG DT codebase.

https://quarkus.io/guides/building-native-image

**Comment by mehab** [comment]
Looking into this issue :)

**Comment by mehab** [comment]
Cache changes that were needed have been added and merged to main branch

**Comment by mehab** [comment]
The native executable for vulnerability-analyzer build and tested successfully. Also able to create native binary image in github actions as can be seen here: https://github.com/mehab/DTKafkaPOC/actions/runs/3836867063 and changes have been merged into main: https://github.com/mehab/DTKafkaPOC/blob/main/.github/workflows/publishNativeBinary.yml

**Comment by mehab** [comment]
There are build issues for building graalvm based native image with the notification-publisher and repo-meta analyzer modules which need to be addressed. It has been seen in the error logs that alpine dependency is trying to use a file that does not exist because of which the native binary build is failing on step 2 of the native image building process.

**Comment by mehab** [comment]
Draft PR created here: https://github.com/mehab/DTKafkaPOC/pull/210 Need to add more tests to improve coverage

**Comment by nscuro** [comment]
I think this can be closed. Thanks @mehab for taking care of it! 🙌
